version: '3.9'

services:
  upload-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: upload-service-dev
    ports:
      - "3009:3009"
    environment:
      PORT: 3009
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      my_custom_network:
        ipv4_address: ${APP_IP}

networks:
  my_custom_network:
    external: true

